# 设置默认的 Gradle 命令内存。可以被用户或命令行属性覆盖。
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
# 环境属性
minecraft_version=1.21.1
# Minecraft 版本范围可以使用任何发行版 Minecraft 作为界限。
minecraft_version_range=[1.21.1]
# Neo 版本必须与 Minecraft 版本一致才能获得有效构件
neo_version=21.1.228
# 加载器版本范围只能使用 FML 主要版本作为界限
loader_version_range=[1,)

kubejs_version=2101.7.2-build.363
rhino_version=2101.2.7-build.80
architectury_version=13.0.2
jade_version=15.10.5+neoforge
jei_version=19.27.0.340
curios_version=9.5.1+1.21.1
bcore_version=3.2.1.+
ccl_version=4.6.1.+
ccl_version_max=4.7.0
de_version=3.1.4.632

## 模组属性
mod_id=advanced_little_garbage
mod_name=delicate_little_garbage
# 模组的许可。请在 https://choosealicense.com/ 查看你的选项。默认是 All Rights Reserved。
mod_license=All Rights Reserved
# 模组版本。见 https://semver.org/
mod_version=0.0.2-alpha
# 模组的 group ID。仅在发布为 Maven 仓库工件时重要。
mod_group_id=com.yueyingiop.ALG

mod_authors=yueyingiop
mod_description=为各种mod添加一些小玩意