# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.6)
forge_version=47.4.0
forge_version_range=[47.4.0,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

jade_version=11.13.2+forge
jei_version=15.20.0.112
curios_version=5.12.0+1.20.1
kubejs_version=2001.6.5-build.16
rhino_version=2001.2.3-build.6
architectury_version=9.2.14


## Mod Properties

mod_id=advanced_little_garbage
mod_name=delicate_little_garbage
mod_license=All Rights Reserved
mod_version=0.0.1
mod_group_id=com.core.ALG
mod_authors=yueyingiop
mod_description=为各种mod添加一些小玩意

