modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
为各种mod添加一些小玩意
'''


[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="curios" # 饰品
    type="optional"
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="draconicevolution" # 龙之研究
    type="optional"
    versionRange="[${de_version},)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="${mod_id}.mixins.json"